import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex min-h-screen bg-gray-100"
      >
        <div className="flex h-screen bg-gray-50 w-full">
          {/* Sidebar */}
          <div className="w-64 bg-[#1E293B] text-white fixed top-0 left-0 h-full z-40">
            <Sidebar />
          </div>

          {/* Contenido principal */}
          <div className="flex flex-col flex-1 ml-64">
            {/* Navbar */}
            <div className="h-16 bg-white shadow-sm fixed top-0 left-64 right-0 z-30">
              <Navbar />
            </div>

            {/* Contenido dinámico */}
            <main className="flex w-full overflow-y-auto mt-16 p-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
